name: Promote and Provision Application Version ID from mule xml
on:
  push: 
    branches: [ main ]

env: 
  SOLACE_MESSAGING_SERVICE: PRODUCTION-solace

jobs:
  promote-provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Get all changed xml files
        id: changed-xml-files
        uses: tj-actions/changed-files@v40
        with:
          files: | 
            **.xml

      - name: Read Mule XML content
        id: mule_xml
        run: |
          for file in ${{ steps.changed-xml-files.outputs.all_changed_files }}; do
            echo -e "xml<<EOF\n$(cat $file)\nEOF" >> $GITHUB_OUTPUT
          done
      
      - name: Extract Application Version ID from Mule config
        uses: tmelliottjr/extract-regex-action@v1.4.0
        id: epApplicationVersionId
        with:
          regex: '(?<=name=\"epApplicationVersionId\" value=\")(.*)(?=\")' 
          flags: "gm"
          input: ${{steps.mule_xml.outputs.xml}}

      - name: Echo Application Version ID
        run: echo "Promoting Application Version ID ${{ steps.epApplicationVersionId.outputs.resultString }}"

      - name: Promote and Provision Application
        if: ${{ steps.epApplicationVersionId.outputs.resultString }}
        uses: SolaceDev/solace-ep-provisioning-github-action@v1.9.11
        with:
          BROKER_TYPE: solace
          SOLACE_MESSAGING_SERVICE: ${{ env.SOLACE_MESSAGING_SERVICE }}
          SOLACE_CLOUD_TOKEN: ${{ secrets.SOLACE_CLOUD_TOKEN }}
          TF_VAR_solace_url: ${{ secrets.TF_VAR_solace_url }}
          TF_VAR_semp_username: ${{ secrets.TF_VAR_semp_username }}
          TF_VAR_semp_password: ${{ secrets.TF_VAR_semp_password }}
          SOL_MSG_VPN: ${{ secrets.SOL_MSG_VPN }}
          APPLICATION_VERSION_ID: ${{ steps.epApplicationVersionId.outputs.resultString }}
